project_id = "talqitzvchxggkqnnmbf"

[functions.submit-traffic-report]
verify_jwt = false

[functions.submit-incident-report]
verify_jwt = false

[functions.submit-chat-message]
verify_jwt = false

[functions.record-visit]
verify_jwt = false

[functions.create-donation-payment]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.get-traffic-data]
verify_jwt = false

[functions.submit-street-vote]
verify_jwt = false

[functions.fetch-rss-feed]
verify_jwt = false
